### PR TITLE
Travis-CI Added newer PHP versions (5.6, 7) and newer Symfony versions

### PR DESCRIPTION
**Pull request by mhlavac**

### CODE REVIEW

**Comment by tomas-pecserke** [comment]
Was the minimum PHP version of 5.**3**.9 motivated by change by Symfony framework?
If so, it should have been 5.**5**.9. Or was there another reason?

Either way, I'd like to maintain compatibility with older version of PHP for use with Symfony <3.0. That way the framework will force the minimum version of PHP.

**Comment by mhlavac** [comment]
@tomas-pecserke the version was set to 5.3.9 because that's minimum for Symfony 2.8 https://packagist.org/packages/symfony/symfony#v2.8.2

**Comment by tomas-pecserke** [comment]
@mhlavac Yeah, I totally forgot about that. I'll have a look at how Symfony guys test against that.

**Comment by tomas-pecserke** [comment]
@mhlavac Well, it seem they don't, nor do FOS. I think we won't either.

**Pull request merged**
